name: Create issues from todos

on:
  push:
    branches:
     - main

jobs:
  todos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: todo-actions
        uses: dtinth/todo-actions@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}
